console.log("hello world all set")
console.log("i am good")
console.log("how are you baby from master from main")
console.log("i am fine")
console.log("i am fine")
console.log("i am beautiful and you also")
console.log("hello world all set")
console.log("i am good")
console.log("how are you baby from master from main")
console.log("i am fine")
console.log("i am fine")
console.log("i am beautiful")


console.log("all good")
